name: No-IP Auto Renew

on:
  schedule:
    # Runs every Sunday at 11:35 UTC
    - cron: '35 11 * * 0'
  workflow_dispatch:  # Enables manual triggering from the Actions tab

jobs:
  renew:
    runs-on: ubuntu-latest

    steps:
      - name: Run No-IP Renewal
        env:
          NOIP_USERNAME: ${{ secrets.NOIP_USERNAME }}
          NOIP_PASSWORD: ${{ secrets.NOIP_PASSWORD }}
          NOIP_TOTP_SECRET: ${{ secrets.NOIP_TOTP_SECRET }}
        run: |
          # Ensure the screenshots directory exists
          mkdir -p ${{ github.workspace }}/screenshots
          docker run --rm -v ${{ github.workspace }}/screenshots:/app/screenshots kirbah/noip-renew:latest \
            -u "$NOIP_USERNAME" -p "$NOIP_PASSWORD" -s "$NOIP_TOTP_SECRET" -d DEBUG

