name: No-IP Auto Renew

on:
  schedule:
    # Runs every Saturday at 09:35 UTC
    - cron: "35 9 * * 0"
  workflow_dispatch: # Enables manual triggering from the Actions tab

jobs:
  renew:
    runs-on: ubuntu-latest

    steps:
      - name: Run No-IP Renewal
        env:
          NOIP_USERNAME: ${{ secrets.NOIP_USERNAME }}
          NOIP_PASSWORD: ${{ secrets.NOIP_PASSWORD }}
          NOIP_TOTP_SECRET: ${{ secrets.NOIP_TOTP_SECRET }}
        run: |
          # Ensure the screenshots directory exists
          mkdir -p ${{ github.workspace }}/screenshots
          docker run --rm -v ${{ github.workspace }}/screenshots:/app/screenshots thatguyjohn/noip-renew:latest \
            -u "$NOIP_USERNAME" -p "$NOIP_PASSWORD" -s "$NOIP_TOTP_SECRET" -d DEBUG

      - name: Upload Screenshots (if any)
        if: always() # Always run this step, even if previous steps fail
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: ${{ github.workspace }}/screenshots
